# Generated by Django 2.2.12 on 2020-05-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20200519_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbank',
            name='upi_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
