# Generated by Django 2.2.12 on 2020-05-28 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0009_userbank_upi_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBankUPIQR',
            fields=[
                ('sn', models.AutoField(primary_key=True, serialize=False)),
                ('pay_ammount', models.CharField(blank=True, max_length=10, null=True)),
                ('upi1', models.CharField(blank=True, max_length=30, null=True)),
                ('upi2', models.CharField(blank=True, max_length=30, null=True)),
                ('qr1', models.ImageField(blank=True, null=True, upload_to='client/qrcode')),
                ('qr2', models.ImageField(blank=True, null=True, upload_to='client/qrcode')),
                ('account_holder_name', models.CharField(blank=True, max_length=30, null=True)),
                ('account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=60, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('sn', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.CharField(blank=True, max_length=10, null=True)),
                ('upi_or_account', models.CharField(blank=True, max_length=30, null=True)),
                ('txt_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('0', 'Failed'), ('1', 'Success')], default='1', max_length=10, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('Membership_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_slip', models.ImageField(blank=True, null=True, upload_to='client/transactionSlip')),
                ('amount', models.CharField(blank=True, max_length=5, null=True)),
                ('status', models.CharField(blank=True, choices=[('0', 'Inactiveted'), ('1', 'Activated')], default='0', max_length=10, null=True)),
                ('txt_date', models.DateField()),
                ('exp_date', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
