# Generated by Django 2.2.12 on 2020-05-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_auto_20200528_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='txt_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
