# Generated by Django 2.2.12 on 2020-05-28 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_auto_20200528_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companybankupiqr',
            old_name='qr1',
            new_name='qr_code',
        ),
        migrations.RenameField(
            model_name='companybankupiqr',
            old_name='upi1',
            new_name='upi_id',
        ),
        migrations.RemoveField(
            model_name='companybankupiqr',
            name='qr2',
        ),
        migrations.RemoveField(
            model_name='companybankupiqr',
            name='upi2',
        ),
    ]
